language: node_js
node_js:
  - "node"
  - "lts/*"
jobs:
  include:
    - stage: test
      script: yarn run build && yarn run test
    - stage: build
      script: yarn run build
      deploy:
        provider: pages
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./build
        verbose: true
        edge: true
        on:
          branch: master
